ALTER TABLE rooms
  ADD COLUMN IF NOT EXISTS version INT UNSIGNED NOT NULL DEFAULT 1 AFTER status;

ALTER TABLE rooms
  ADD COLUMN IF NOT EXISTS player_tokens_json MEDIUMTEXT DEFAULT NULL AFTER player2_token,
  ADD COLUMN IF NOT EXISTS host_token VARCHAR(64) DEFAULT NULL AFTER player_tokens_json,
  ADD COLUMN IF NOT EXISTS max_players TINYINT UNSIGNED NOT NULL DEFAULT 2 AFTER host_token;
