CREATE TABLE IF NOT EXISTS rooms (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  code VARCHAR(8) NOT NULL,
  state_json MEDIUMTEXT NOT NULL,
  player1_token VARCHAR(64) NOT NULL,
  player2_token VARCHAR(64) DEFAULT NULL,
  player_tokens_json MEDIUMTEXT DEFAULT NULL,
  host_token VARCHAR(64) DEFAULT NULL,
  max_players TINYINT UNSIGNED NOT NULL DEFAULT 2,
  status ENUM('waiting', 'active', 'finished') NOT NULL DEFAULT 'waiting',
  version INT UNSIGNED NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY rooms_code_unique (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
